[package]
name = "json_placeholder"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_rest_api = { path = "../../derive_rest_api", features = ["reqwest-blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "1.0.0-rc.3"
